language: python
services:
  - docker
python:
  - "2.7"
install:
  - make deps
script:
  - make test
  - make lint
  - make docker_build
  - make docker_run
  - sleep 2; python test-api/test_api.py
after success:
  - make docker_push

deploy:
  provider: heroku
  app: ancient-sea-62343
  api_key: ${HEROKU_API_KEY}
